### ISSUE TITLE
wrong behavior if the property is Set | null

### ISSUE THREAD

**Issue by fuyifan** [asvetliakov/orm-redis#3]
if you define the property as Set | null, in the getSaveOperation function 
`hasPrototypeOf(valueType, Set) || hasPrototypeOf(valueType, Map) || hasPrototypeOf(valueType, LazySet) || hasPrototypeOf(valueType, LazyMap)` is false, coz Set | null is taken as Object. So the following code that handle the Set or Map behavior will not run as expected.

**Comment by asvetliakov** [comment]
This is TS ```emitDecoratorsMetadata``` behavior - any nullable type becomes ```Object``` in emitted metadata. 
Just use this to fix:

```ts
@Property(Set)
public someSet: Set | null = null;
```

**Comment by fuyifan** [comment]
Yes, i think its better popup some warning message when the parameter is empty but the type is js object.
________________________________
发件人: Alexey Svetliakov <notifications@github.com>
发送时间: 2018年5月18日 18:59
收件人: asvetliakov/orm-redis
抄送: fuyifan; Author
主题: Re: [asvetliakov/orm-redis] wrong behavior if the property is Set | null (#3)


This is TS emitDecoratorsMetadata behavior - any nullable type becomes Object.
Just use this:

@Property(Set)
public someSet: Set | null = null;

―

**Comment by asvetliakov** [comment]
The Object is valid type too - it's being serialized to JSON string. So these will give you unexpected warnings

```ts
@Property()
prop1: Object;

@Property()
prop2: { [key: string]: string };
```
I'd recommend to always use parameter type in ```@Property()```, without leveraging ```emitDecoratorMetadata```
